// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUVOrBS7mT-BwbOn3E5MLw7LXi71kbJG8',
    appId: '1:428651767494:web:070c19a31a7adff904d9c7',
    messagingSenderId: '428651767494',
    projectId: 'books-genie',
    authDomain: 'books-genie.firebaseapp.com',
    storageBucket: 'books-genie.appspot.com',
    measurementId: 'G-SGC7LKYXLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgHhQwvV2rQBUIsxtQENPCuyu8foZkvOM',
    appId: '1:428651767494:android:4e109a48d4ba263c04d9c7',
    messagingSenderId: '428651767494',
    projectId: 'books-genie',
    storageBucket: 'books-genie.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSF2Uw8ZppUZ4JIHQVVg2ceyJKSGj8tgA',
    appId: '1:428651767494:ios:ff74bf67179f37f604d9c7',
    messagingSenderId: '428651767494',
    projectId: 'books-genie',
    storageBucket: 'books-genie.appspot.com',
    androidClientId: '428651767494-v8hc05mr0ejtk3nlapecrvsl38ugs58v.apps.googleusercontent.com',
    iosClientId: '428651767494-aqccs4t5plc43rhke5sjg49no7b1m5qc.apps.googleusercontent.com',
    iosBundleId: 'com.example.myClinicScreenshots',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSF2Uw8ZppUZ4JIHQVVg2ceyJKSGj8tgA',
    appId: '1:428651767494:ios:ff74bf67179f37f604d9c7',
    messagingSenderId: '428651767494',
    projectId: 'books-genie',
    storageBucket: 'books-genie.appspot.com',
    androidClientId: '428651767494-v8hc05mr0ejtk3nlapecrvsl38ugs58v.apps.googleusercontent.com',
    iosClientId: '428651767494-aqccs4t5plc43rhke5sjg49no7b1m5qc.apps.googleusercontent.com',
    iosBundleId: 'com.example.myClinicScreenshots',
  );
}
